from .prompts.prmt_main import (
    MENSAGEM_INICIAL, MENSAGEM_DE_DESPEDIDA, BOAS_PRATICAS,
    OBJETIVOS, PERSONA, DIRETRIZES, DADOS_DE_ENTRADA
)

ORCHESTRATOR_PRMT: str = PERSONA + MENSAGEM_INICIAL + OBJETIVOS + DADOS_DE_ENTRADA + DIRETRIZES + BOAS_PRATICAS + MENSAGEM_DE_DESPEDIDA